language:      node_js
git:
  depth:       3
node_js:
  - "20"
install:       npm ci
script:
  - npm audit --audit-level=high
  - npm test
  - gulp
cache:
  directories:
    - node_modules
notifications:
  email:       false
